# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38c65f9091164cd66cbe313437c8cd188745edc06ea824989c9acd48df7efaec84fba71a84f9cf40ec031c38da1c26ecd573a398013c951b84e2d1a1081831aa

test:
  secret_key_base: fa1a3ea8a5f683af7a4d566797c9dcf917dbaff86daa729e9695a77a5d488f1269d680ef9c4fdeb307430085f3ff2ff092cdbd90cfd4fbbcc472f39ec7489178

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
